// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk4W5wdZgrHVTPO5MzkIdt5f9eQxJ6LB4',
    appId: '1:990531650984:web:5c9930f8814e0961f5099d',
    messagingSenderId: '990531650984',
    projectId: 'mad-beast-mode',
    authDomain: 'mad-beast-mode.firebaseapp.com',
    storageBucket: 'mad-beast-mode.firebasestorage.app',
    measurementId: 'G-7J12EZXCFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0cMswjo0aJ2hygzuDcIMTWzdFIj0t2FA',
    appId: '1:990531650984:android:06b89a011741d7eff5099d',
    messagingSenderId: '990531650984',
    projectId: 'mad-beast-mode',
    storageBucket: 'mad-beast-mode.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvxorsftZUs9hAm1RxLpk6Ljp4rJ_dxQ0',
    appId: '1:990531650984:ios:8dccfebd1adbe4c6f5099d',
    messagingSenderId: '990531650984',
    projectId: 'mad-beast-mode',
    storageBucket: 'mad-beast-mode.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvxorsftZUs9hAm1RxLpk6Ljp4rJ_dxQ0',
    appId: '1:990531650984:ios:8dccfebd1adbe4c6f5099d',
    messagingSenderId: '990531650984',
    projectId: 'mad-beast-mode',
    storageBucket: 'mad-beast-mode.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk4W5wdZgrHVTPO5MzkIdt5f9eQxJ6LB4',
    appId: '1:990531650984:web:ff4e111eff63038ef5099d',
    messagingSenderId: '990531650984',
    projectId: 'mad-beast-mode',
    authDomain: 'mad-beast-mode.firebaseapp.com',
    storageBucket: 'mad-beast-mode.firebasestorage.app',
    measurementId: 'G-C6DTQ710GT',
  );
}
